### ISSUE TITLE
Bug 게시판 추천 누를 시 조회수가 계속 올라감

### ISSUE THREAD

**Issue by dustnehowl** [MBTIWithUs/MBTIWithUs-FE#20]
# Bug 사항
- 게시글 추천을 누를 시 조회수가 계속 올라가는 버그(아래 그림 참고)
![image](https://user-images.githubusercontent.com/39877181/205835755-162e6540-d7df-4629-94c5-02a9b01011ad.png)

**Comment by ha4219** [comment]
#21
