### ISSUE TITLE
Bug 공감을 취소할 경우 조회 수가 내려가는 버그

### ISSUE THREAD

**Issue by dustnehowl** [MBTIWithUs/MBTIWithUs-FE#22]
![image](https://user-images.githubusercontent.com/39877181/206252779-af99930c-9184-4264-bca0-0daddd560f05.png)

- 공감을 취소하기 전 조회 수 : 5
- 공감을 취소한 후 조회 수 : 2

![image](https://user-images.githubusercontent.com/39877181/206253024-da46e222-b417-4d64-97d8-e9891f1b1e80.png)

**Comment by ha4219** [comment]
#21 배포 완료
